# https://github.com/sds/overcommit#usage

PreCommit:
  YamlSyntax:
    enabled: true
  RakeTarget:
    enabled: true
    targets:
      - lint
PrePush:
  RakeTarget:
    enabled: true
    targets:
      - lint
      - test
