AllCops:
  NewCops: enable # https://docs.rubocop.org/rubocop/1.11/versioning.html#pending-cops
  SuggestExtensions: false
  TargetRubyVersion: 3.2.2
  Exclude:
    - bin/**/*
    - tmp/**/*
    - vendor/**/*
    - test/**/*
    - lib/shipengine/utils/base58.rb
    - !ruby/regexp /(foo|bar|baz)\.rb/

Style/Documentation:
  Enabled: false

Style/Lambda:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Max: 300
  IgnoredPatterns: ["^ *# "]

Metrics/BlockLength:
  Enabled: false

Layout/MultilineOperationIndentation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
