AllCops:
  NewCops: enable # https://docs.rubocop.org/rubocop/1.11/versioning.html#pending-cops
  TargetRubyVersion: 2.6
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Max: 150
  IgnoredPatterns:  ['^ *# ']

Metrics/BlockLength:
  Enabled: false
