name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened

jobs:
  ci:
    name: Build, Lint, and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Ruby and Build
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Lint
        run: bundle exec rake lint

      - name: Test
        run: bundle exec rake test
